"""
auth_checker.py

Compare the authentication response returned by an SLE4436-compatible card
with the response generated by the reconstructed algorithm.

Tested protocol assumption:
    ACR38 CCID memory-card interface.

For AUTHENTICATE_MEMORY_CARD the CCID interface uses two steps:
    FF 84 ...       -> SW = 61 02
    FF C0 00 00 02 -> CERT(2 bytes), SW = 90 00
"""

from Cryptodome.Cipher import DES3
from response_generator import ResponseGenerator
from secret import RESPONSE_GENERATOR_CONFIG, MASTER_KEY
from secrets import token_bytes
from smartcard.System import readers


SW_SUCCESS = 0x9000
SW_AUTH_RESPONSE_READY = 0x6102


# =====================================================================
# Card access
# =====================================================================

def _transmit(connection, apdu):
    """Transmit APDU and return (data as bytes, SW1SW2 as a 16-bit int)."""
    data, sw1, sw2 = connection.transmit(list(apdu))
    return bytes(data), (sw1 << 8) | sw2


def set_card_type_104(connection):
    """Select ACR38 card type 07: SLE4406/SLE4436/SLE5536/SLE6636."""
    _, sw = _transmit(connection, bytes.fromhex("FF A4 00 00 01 07"))
    return sw == SW_SUCCESS


def get_card_atr(connection):
    return bytes(connection.getATR())


def read_card(connection):
    """Read card memory and remove a repeated tail if the reader returns one."""
    data, sw = _transmit(connection, bytes.fromhex("FF B0 00 00 80"))

    if sw != SW_SUCCESS:
        return False, b""

    if len(data) >= 8:
        repeat_index = data.find(data[:8], 8)
        if repeat_index >= 0:
            data = data[:repeat_index]

    return True, data


def auth_card(connection, key_index, cbc, challenge):
    """
    Request the 16-bit authentication response from the card.

    key_index:
        0 -> Key 1
        1 -> Key 2

    cbc:
        False -> no cipher block chaining
        True  -> cipher block chaining

    challenge:
        exactly 6 bytes
    """
    if key_index not in (0, 1):
        raise ValueError("key_index must be 0 or 1")

    if type(cbc) is not bool:
        raise TypeError("cbc must be bool")

    if len(challenge) != 6:
        raise ValueError("challenge must contain exactly 6 bytes")

    key_flags = (0x80 if cbc else 0) | key_index

    authenticate_apdu = bytes.fromhex(
        f"FF 84 00 00 08 {key_flags:02X} A0 {challenge.hex()}"
    )

    data, sw = _transmit(connection, authenticate_apdu)

    # ACR38 CCID: successful AUTHENTICATE_MEMORY_CARD normally returns
    # 61 02, meaning that two bytes are ready for GET RESPONSE.
    if sw == SW_AUTH_RESPONSE_READY:
        data, sw = _transmit(
            connection,
            bytes.fromhex("FF C0 00 00 02"),
        )

        if sw != SW_SUCCESS or len(data) < 2:
            return False, b""

        return True, data[:2]

    # Some older/non-CCID ACR38 interfaces are documented as returning
    # CERT directly with 90 00. Supporting that variant costs almost nothing
    # and keeps the helper usable with both behaviours.
    if sw == SW_SUCCESS and len(data) >= 2:
        return True, data[:2]

    return False, b""


# =====================================================================
# RUN
# =====================================================================

def main():
    generator = ResponseGenerator(**RESPONSE_GENERATOR_CONFIG)

    available_readers = readers()
    print(available_readers)

    connection = None

    for reader in available_readers:
        try:
            candidate = reader.createConnection()
            candidate.connect()
            connection = candidate
            print(f"Connected to reader {reader}.")
            break
        except Exception as exc:
            print(f"Can't connect to reader {reader}: {exc}")

    if connection is None:
        raise RuntimeError("No usable smart-card reader found")

    print("Reading.")

    atr = get_card_atr(connection)
    print(f"ATR = {atr.hex().upper()}.")

    if not set_card_type_104(connection):
        raise RuntimeError("Failed to select card type 104")

    read_ok, dump = read_card(connection)
    if not read_ok:
        raise RuntimeError("Failed to read card")

    if len(dump) < 16:
        raise RuntimeError(
            f"Card dump is too short: {len(dump)} bytes, expected at least 16"
        )

    cipher = DES3.new(bytes.fromhex(MASTER_KEY), DES3.MODE_ECB)
    kc = cipher.encrypt(dump[:8])[:6]

    ok = 0
    bogus = 0
    errors = 0

    for _ in range(100):
        challenge = token_bytes(6)

        auth_ok, card_response = auth_card(
            connection,
            key_index=0,
            cbc=False,
            challenge=challenge,
        )

        if not auth_ok:
            print(f"Challenge:             {challenge.hex(' ').upper()}")
            print("Card authentication command failed.")
            print()
            errors += 1
            continue

        vsam_response = generator.generate_response(
            dump[:16] + kc + challenge
        )

        print(f"Challenge:             {challenge.hex(' ').upper()}")
        print(f"Card Response:         {card_response.hex(' ').upper()}")
        print(f"Virtual SAM Response:  {vsam_response.hex(' ').upper()}")

        if card_response == vsam_response:
            print("Card OK!")
            ok += 1
        else:
            print("Bogus card.")
            bogus += 1

        print()

    print(f"OK = {ok}, bogus = {bogus}, errors = {errors}")


if __name__ == "__main__":
    main()
